name = "Ende"
author = "vBlue"
version = "24.09.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9157996358e9f22d6b62d4774c226698acab88a5f958500d9ecf9f78e28546ba"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
