name = "Ende"
author = "vBlue"
version = "24.09.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "177077536a3abab3492319d7b4ffbde49f0de40a3418ab835e58d4c87137d221"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
