[general]

[general.general]
timestamps_format = 0
streamer_mode = false
modcore_warning = true

[general.online_status]
show_essential_indicator_on_tab = true
show_essential_indicator_on_nametags = true

[general.experience]
essential_menu_layout = 0
enable_essential = true
quick_action_bar = false
use_vanilla_button_texture = false
darken_re-textured_menu_buttons = false
closer_placement_of_minimal_essential_menu = true

[hidden]
previously_launched_with_container = 1

[hidden.hidden]
emote_perspective = 1
spspinnedgamerules = ""
coinsselectedcurrency = "USD"
screenshotbrowseritemsperrow = 3
showemotepagekeybindbanner = true
coinspurchasecreatorcode = "__default__"

[emotes]

[emotes.general]
emote_preview = false
disable_emotes = false
play_emotes_in_third_person_view = true

[privacy]

[privacy.general]
friend_privacy_settings = 0
display_current_server = false

[notifications]

[notifications.general]
message_sound = true
online_friend_alert = true
update_notifications = true
host_world_ip_warning = true
message_notifications = true
disable_all_notifications = false
group_message_notifications = true
screenshot_toast_duration = 1

[notifications.warnings]
link_opening_warning = true

[quality_of_life]

[quality_of_life.general]
auto_refresh_session = true

[quality_of_life.accessibility]
enlarge_chat_metadata = false

[quality_of_life.discord_integration]
set_activity_status_on_discord = true
show_username_and_avatar = true
show_current_server = false
allow_ask_to_join = true

[quality_of_life.zoom]
toggle_to_zoom = false
smooth_zoom_animation = false
smooth_camera_when_zoomed = true

[quality_of_life.screenshots]
screenshot_sounds = true
essential_screenshots = true
vanilla_screenshot_message = false

post_screenshot_action = 0
"screenshot_quick_action_#1_-_top_left" = 5
"screenshot_quick_action_#2_-_top_right" = 2
"screenshot_quick_action_#3_-_bottom_left" = 0
"screenshot_quick_action_#4_-_bottom_right" = 4

[__meta]
version = 12

[cosmetics]

[cosmetics.general]
disable_cosmetics = false
hide_cosmetics_on_server_skins = false
disable_cosmetics_in_inventory = false
"cosmetic_&_armor_conflict_-_on_myself" = 0
"cosmetic_&_armor_conflict_-_on_others" = 0
